### ISSUE TITLE
gitee黑色背景时应用浅色logo

### ISSUE THREAD

**Issue by chenxuuu** [userElaina/this-is-the-China-website#1]
https://gitee.com/static/images/logo.svg

![图片](https://user-images.githubusercontent.com/10357394/197709965-970b75dc-2afb-4594-a43c-083b8eba87c1.png)

**Comment by userElaina** [comment]
done [c45732d](https://github.com/userElaina/this-is-the-China-website/commit/c45732d88fbe1f360c35fea7ba60872b3a146461)
