### ISSUE TITLE
谷歌学术 伪装成 百度学术

### ISSUE THREAD

**Issue by Grand-Magus** [userElaina/this-is-the-China-website#11]

**Comment by userElaina** [comment]
好

**Comment by Grand-Magus** [comment]
您发给我的信件已经收到。This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by userElaina** [comment]
done

**Comment by Grand-Magus** [comment]
您发给我的信件已经收到。This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by Grand-Magus** [comment]
您发给我的信件已经收到。This is an automatic reply, confirming that your e-mail was received.Thank you
