### ISSUE TITLE
强烈推荐把youtube图标替换成西瓜视频（西瓜视频的页面和youtube相似度极高）

### ISSUE THREAD

**Issue by elsakane2015** [userElaina/this-is-the-China-website#8]
强烈推荐把youtube图标替换成西瓜视频（西瓜视频的页面和youtube相似度极高）

**Comment by userElaina** [comment]
好。感谢反馈。

**Comment by userElaina** [comment]
done [35776d0](https://github.com/userElaina/this-is-the-China-website/commit/35776d0d72c0ce196388ffacb7b14bcc527ff522)
